/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RecruiterRouteImport } from './routes/recruiter'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as CandidateRouteImport } from './routes/candidate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecruiterIndexRouteImport } from './routes/recruiter.index'
import { Route as CandidateIndexRouteImport } from './routes/candidate.index'
import { Route as RecruiterUploadRouteImport } from './routes/recruiter.upload'
import { Route as RecruiterPipelineRouteImport } from './routes/recruiter.pipeline'
import { Route as RecruiterCompareRouteImport } from './routes/recruiter.compare'
import { Route as RecruiterCandidatesRouteImport } from './routes/recruiter.candidates'
import { Route as RecruiterAnalyticsRouteImport } from './routes/recruiter.analytics'
import { Route as CandidateReportRouteImport } from './routes/candidate.report'
import { Route as CandidateProfileRouteImport } from './routes/candidate.profile'
import { Route as CandidatePrepareRouteImport } from './routes/candidate.prepare'
import { Route as CandidateInterviewRouteImport } from './routes/candidate.interview'
import { Route as CandidateImproveRouteImport } from './routes/candidate.improve'
import { Route as CandidateHistoryRouteImport } from './routes/candidate.history'
import { Route as RecruiterCandidateIdRouteImport } from './routes/recruiter.candidate.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterRoute = RecruiterRouteImport.update({
  id: '/recruiter',
  path: '/recruiter',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateRoute = CandidateRouteImport.update({
  id: '/candidate',
  path: '/candidate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterIndexRoute = RecruiterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecruiterRoute,
} as any)
const CandidateIndexRoute = CandidateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CandidateRoute,
} as any)
const RecruiterUploadRoute = RecruiterUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterPipelineRoute = RecruiterPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterCompareRoute = RecruiterCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterCandidatesRoute = RecruiterCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => RecruiterRoute,
} as any)
const RecruiterAnalyticsRoute = RecruiterAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => RecruiterRoute,
} as any)
const CandidateReportRoute = CandidateReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateProfileRoute = CandidateProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidatePrepareRoute = CandidatePrepareRouteImport.update({
  id: '/prepare',
  path: '/prepare',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateInterviewRoute = CandidateInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateImproveRoute = CandidateImproveRouteImport.update({
  id: '/improve',
  path: '/improve',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateHistoryRoute = CandidateHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => CandidateRoute,
} as any)
const RecruiterCandidateIdRoute = RecruiterCandidateIdRouteImport.update({
  id: '/candidate/$id',
  path: '/candidate/$id',
  getParentRoute: () => RecruiterRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/candidate': typeof CandidateRouteWithChildren
  '/portal': typeof PortalRoute
  '/recruiter': typeof RecruiterRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/candidate/history': typeof CandidateHistoryRoute
  '/candidate/improve': typeof CandidateImproveRoute
  '/candidate/interview': typeof CandidateInterviewRoute
  '/candidate/prepare': typeof CandidatePrepareRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/report': typeof CandidateReportRoute
  '/recruiter/analytics': typeof RecruiterAnalyticsRoute
  '/recruiter/candidates': typeof RecruiterCandidatesRoute
  '/recruiter/compare': typeof RecruiterCompareRoute
  '/recruiter/pipeline': typeof RecruiterPipelineRoute
  '/recruiter/upload': typeof RecruiterUploadRoute
  '/candidate/': typeof CandidateIndexRoute
  '/recruiter/': typeof RecruiterIndexRoute
  '/recruiter/candidate/$id': typeof RecruiterCandidateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/portal': typeof PortalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/candidate/history': typeof CandidateHistoryRoute
  '/candidate/improve': typeof CandidateImproveRoute
  '/candidate/interview': typeof CandidateInterviewRoute
  '/candidate/prepare': typeof CandidatePrepareRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/report': typeof CandidateReportRoute
  '/recruiter/analytics': typeof RecruiterAnalyticsRoute
  '/recruiter/candidates': typeof RecruiterCandidatesRoute
  '/recruiter/compare': typeof RecruiterCompareRoute
  '/recruiter/pipeline': typeof RecruiterPipelineRoute
  '/recruiter/upload': typeof RecruiterUploadRoute
  '/candidate': typeof CandidateIndexRoute
  '/recruiter': typeof RecruiterIndexRoute
  '/recruiter/candidate/$id': typeof RecruiterCandidateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/candidate': typeof CandidateRouteWithChildren
  '/portal': typeof PortalRoute
  '/recruiter': typeof RecruiterRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/candidate/history': typeof CandidateHistoryRoute
  '/candidate/improve': typeof CandidateImproveRoute
  '/candidate/interview': typeof CandidateInterviewRoute
  '/candidate/prepare': typeof CandidatePrepareRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/report': typeof CandidateReportRoute
  '/recruiter/analytics': typeof RecruiterAnalyticsRoute
  '/recruiter/candidates': typeof RecruiterCandidatesRoute
  '/recruiter/compare': typeof RecruiterCompareRoute
  '/recruiter/pipeline': typeof RecruiterPipelineRoute
  '/recruiter/upload': typeof RecruiterUploadRoute
  '/candidate/': typeof CandidateIndexRoute
  '/recruiter/': typeof RecruiterIndexRoute
  '/recruiter/candidate/$id': typeof RecruiterCandidateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/candidate'
    | '/portal'
    | '/recruiter'
    | '/sitemap.xml'
    | '/candidate/history'
    | '/candidate/improve'
    | '/candidate/interview'
    | '/candidate/prepare'
    | '/candidate/profile'
    | '/candidate/report'
    | '/recruiter/analytics'
    | '/recruiter/candidates'
    | '/recruiter/compare'
    | '/recruiter/pipeline'
    | '/recruiter/upload'
    | '/candidate/'
    | '/recruiter/'
    | '/recruiter/candidate/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/portal'
    | '/sitemap.xml'
    | '/candidate/history'
    | '/candidate/improve'
    | '/candidate/interview'
    | '/candidate/prepare'
    | '/candidate/profile'
    | '/candidate/report'
    | '/recruiter/analytics'
    | '/recruiter/candidates'
    | '/recruiter/compare'
    | '/recruiter/pipeline'
    | '/recruiter/upload'
    | '/candidate'
    | '/recruiter'
    | '/recruiter/candidate/$id'
  id:
    | '__root__'
    | '/'
    | '/candidate'
    | '/portal'
    | '/recruiter'
    | '/sitemap.xml'
    | '/candidate/history'
    | '/candidate/improve'
    | '/candidate/interview'
    | '/candidate/prepare'
    | '/candidate/profile'
    | '/candidate/report'
    | '/recruiter/analytics'
    | '/recruiter/candidates'
    | '/recruiter/compare'
    | '/recruiter/pipeline'
    | '/recruiter/upload'
    | '/candidate/'
    | '/recruiter/'
    | '/recruiter/candidate/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CandidateRoute: typeof CandidateRouteWithChildren
  PortalRoute: typeof PortalRoute
  RecruiterRoute: typeof RecruiterRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter': {
      id: '/recruiter'
      path: '/recruiter'
      fullPath: '/recruiter'
      preLoaderRoute: typeof RecruiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate': {
      id: '/candidate'
      path: '/candidate'
      fullPath: '/candidate'
      preLoaderRoute: typeof CandidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/': {
      id: '/recruiter/'
      path: '/'
      fullPath: '/recruiter/'
      preLoaderRoute: typeof RecruiterIndexRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/candidate/': {
      id: '/candidate/'
      path: '/'
      fullPath: '/candidate/'
      preLoaderRoute: typeof CandidateIndexRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/recruiter/upload': {
      id: '/recruiter/upload'
      path: '/upload'
      fullPath: '/recruiter/upload'
      preLoaderRoute: typeof RecruiterUploadRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/pipeline': {
      id: '/recruiter/pipeline'
      path: '/pipeline'
      fullPath: '/recruiter/pipeline'
      preLoaderRoute: typeof RecruiterPipelineRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/compare': {
      id: '/recruiter/compare'
      path: '/compare'
      fullPath: '/recruiter/compare'
      preLoaderRoute: typeof RecruiterCompareRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/candidates': {
      id: '/recruiter/candidates'
      path: '/candidates'
      fullPath: '/recruiter/candidates'
      preLoaderRoute: typeof RecruiterCandidatesRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/recruiter/analytics': {
      id: '/recruiter/analytics'
      path: '/analytics'
      fullPath: '/recruiter/analytics'
      preLoaderRoute: typeof RecruiterAnalyticsRouteImport
      parentRoute: typeof RecruiterRoute
    }
    '/candidate/report': {
      id: '/candidate/report'
      path: '/report'
      fullPath: '/candidate/report'
      preLoaderRoute: typeof CandidateReportRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/profile': {
      id: '/candidate/profile'
      path: '/profile'
      fullPath: '/candidate/profile'
      preLoaderRoute: typeof CandidateProfileRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/prepare': {
      id: '/candidate/prepare'
      path: '/prepare'
      fullPath: '/candidate/prepare'
      preLoaderRoute: typeof CandidatePrepareRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/interview': {
      id: '/candidate/interview'
      path: '/interview'
      fullPath: '/candidate/interview'
      preLoaderRoute: typeof CandidateInterviewRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/improve': {
      id: '/candidate/improve'
      path: '/improve'
      fullPath: '/candidate/improve'
      preLoaderRoute: typeof CandidateImproveRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/history': {
      id: '/candidate/history'
      path: '/history'
      fullPath: '/candidate/history'
      preLoaderRoute: typeof CandidateHistoryRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/recruiter/candidate/$id': {
      id: '/recruiter/candidate/$id'
      path: '/candidate/$id'
      fullPath: '/recruiter/candidate/$id'
      preLoaderRoute: typeof RecruiterCandidateIdRouteImport
      parentRoute: typeof RecruiterRoute
    }
  }
}

interface CandidateRouteChildren {
  CandidateHistoryRoute: typeof CandidateHistoryRoute
  CandidateImproveRoute: typeof CandidateImproveRoute
  CandidateInterviewRoute: typeof CandidateInterviewRoute
  CandidatePrepareRoute: typeof CandidatePrepareRoute
  CandidateProfileRoute: typeof CandidateProfileRoute
  CandidateReportRoute: typeof CandidateReportRoute
  CandidateIndexRoute: typeof CandidateIndexRoute
}

const CandidateRouteChildren: CandidateRouteChildren = {
  CandidateHistoryRoute: CandidateHistoryRoute,
  CandidateImproveRoute: CandidateImproveRoute,
  CandidateInterviewRoute: CandidateInterviewRoute,
  CandidatePrepareRoute: CandidatePrepareRoute,
  CandidateProfileRoute: CandidateProfileRoute,
  CandidateReportRoute: CandidateReportRoute,
  CandidateIndexRoute: CandidateIndexRoute,
}

const CandidateRouteWithChildren = CandidateRoute._addFileChildren(
  CandidateRouteChildren,
)

interface RecruiterRouteChildren {
  RecruiterAnalyticsRoute: typeof RecruiterAnalyticsRoute
  RecruiterCandidatesRoute: typeof RecruiterCandidatesRoute
  RecruiterCompareRoute: typeof RecruiterCompareRoute
  RecruiterPipelineRoute: typeof RecruiterPipelineRoute
  RecruiterUploadRoute: typeof RecruiterUploadRoute
  RecruiterIndexRoute: typeof RecruiterIndexRoute
  RecruiterCandidateIdRoute: typeof RecruiterCandidateIdRoute
}

const RecruiterRouteChildren: RecruiterRouteChildren = {
  RecruiterAnalyticsRoute: RecruiterAnalyticsRoute,
  RecruiterCandidatesRoute: RecruiterCandidatesRoute,
  RecruiterCompareRoute: RecruiterCompareRoute,
  RecruiterPipelineRoute: RecruiterPipelineRoute,
  RecruiterUploadRoute: RecruiterUploadRoute,
  RecruiterIndexRoute: RecruiterIndexRoute,
  RecruiterCandidateIdRoute: RecruiterCandidateIdRoute,
}

const RecruiterRouteWithChildren = RecruiterRoute._addFileChildren(
  RecruiterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CandidateRoute: CandidateRouteWithChildren,
  PortalRoute: PortalRoute,
  RecruiterRoute: RecruiterRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
